#!/usr/bin/env node
// Regenerates public/sitemap.xml from src/content/maco.ts — replaces the
// hand-maintained list that both CONTEXT.md and sitemap.xml's own comment
// flagged as a staleness risk. Wired into `build` (see package.json); needs
// Node's --experimental-strip-types since content/maco.ts is plain typed
// data (no imports, no non-erasable syntax) with no build step of its own.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { services, projects, products } from "../src/content/maco.ts";

const SITE_URL = "https://www.maco.codes";

const staticPaths = ["/", "/about", "/services", "/work", "/products", "/clients", "/contact"];
const paths = [
  ...staticPaths,
  ...services.map((s) => `/services/${s.slug}`),
  ...projects.map((p) => `/work/${p.slug}`),
  ...products.map((p) => `/products/${p.slug}`),
];

const urls = paths.map((p) => `  <url><loc>${SITE_URL}${p}</loc></url>`).join("\n");
const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs from src/content/maco.ts — do not hand-edit. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

const out = fileURLToPath(new URL("../public/sitemap.xml", import.meta.url));
writeFileSync(out, xml);
console.log(`sitemap.xml written (${paths.length} URLs)`);
